# Generated by Django 3.2.18 on 2023-03-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'author',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authorrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authorRole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nbti',
            fields=[
                ('nbti_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'nbti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('uudi', models.CharField(max_length=45)),
                ('link', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Useranswer',
            fields=[
                ('useranswer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userAnswer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usernbti',
            fields=[
                ('usernbti_id', models.AutoField(db_column='userNbti_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'userNbti',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userwebtoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'userWebtoon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Webtoon',
            fields=[
                ('webtoon_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('platform', models.CharField(blank=True, max_length=5, null=True)),
                ('end_flag', models.IntegerField(blank=True, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('view', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'webtoon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Webtoontag',
            fields=[
                ('webtoontag_id', models.AutoField(db_column='webtoonTag_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'webtoonTag',
                'managed': False,
            },
        ),
    ]
