# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/103Kykaf9QvQDO_FKUgkLLku3cPAEP24q
"""

from google.colab import drive
drive.mount('/content/drive')

from konlpy.tag import Okt
okt = Okt()

import csv

# 빈 리스트 생성
titles = []

# csv 파일 열기
with open('/content/drive/MyDrive/SSAFY/특화프로젝트(A302)/webtoon_data/data_comic_new.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    # 첫 번째 줄은 컬럼명이므로 건너뜀
    columns = next(reader)
    title_idx = columns.index('prdctNm')
    
    # 각 row에서 title과 synopsis 추출하여 리스트에 저장하고, 이를 각각의 리스트에 추가
    for row in reader:
        title = row[title_idx]
        titles.append(title)

# 빈 리스트 생성
title_nounses_list = []

# csv 파일 열기
with open('/content/drive/MyDrive/SSAFY/특화프로젝트(A302)/webtoon_data/data_comic_new.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    # 첫 번째 줄은 컬럼명이므로 건너뜀
    columns = next(reader)
    title_idx = columns.index('prdctNm')

    for row in reader:
        #title
        title = row[title_idx]
        title_nounses = okt.nouns(title)
        for nouns in title_nounses:
            if 1 < len(str(nouns)) :
              temp = [title, nouns]
              title_nounses_list.append(temp)

# 빈 리스트 생성
outline_nounses_list = []

# csv 파일 열기
with open('/content/drive/MyDrive/SSAFY/특화프로젝트(A302)/webtoon_data/data_comic_new.csv', 'r', encoding='utf-8') as f:
    reader = csv.reader(f)
    # 첫 번째 줄은 컬럼명이므로 건너뜀
    columns = next(reader)
    title_idx = columns.index('prdctNm')
    outline_idx = columns.index('outline')

    for row in reader:
        #outline
        outline = row[outline_idx]
        if not outline:
          continue
        outline_nounses = okt.nouns(outline)
        for nouns in outline_nounses:
            if 1 < len(str(nouns)) :
              temp = [title, nouns]
              outline_nounses_list.append(temp)

# titles.csv 파일 생성
with open('/content/drive/MyDrive/SSAFY/특화프로젝트(A302)/webtoon_data/title_keyword.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['title', 'nouns'])
    for item in title_nounses_list:
        writer.writerow(item)

# outline.csv 파일 생성
with open('/content/drive/MyDrive/SSAFY/특화프로젝트(A302)/webtoon_data/outline_keyword.csv', 'w', encoding='utf-8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['title', 'outline'])
    for item in outline_nounses_list:
        writer.writerow(item)